"""
Models package for Vemeego backend.
Exports all Pydantic models for request/response validation.
"""

from app.models.meeting import (
    ChatMessageInput,
    LiveKitTokenResponse,
    MeetingBase,
    MeetingCreate,
    MeetingChatMessageResponse,
    MeetingListResponse,
    MeetingQueryParams,
    MeetingResponse,
    MeetingStatus,
    MeetingType,
    MeetingUpdate,
    ParticipantInput,
    ParticipantResponse,
    ParticipantRole,
    ParticipantStatus,
    ParticipantStatusUpdate,
)
from app.models.message import (
    ConversationListResponse,
    ConversationResponse,
    MessageBase,
    MessageCreate,
    MessageReactionCreate,
    MessageReactionResponse,
    MessageResponse,
    MessageUpdate,
    PinMessageRequest,
)
from app.models.organization import (
    ApproveOrgAdminRequest,
    OrganizationBase,
    OrganizationCreate,
    OrganizationListResponse,
    OrganizationQueryParams,
    OrganizationResponse,
    OrganizationSetup,
    OrganizationSetupResponse,
    OrganizationSubscriptionUpdate,
    OrganizationUpdate,
    OrganizationWithStats,
    OrgAdminSignup,
    OrgAdminSignupResponse,
    SubscriptionPlan,
    SubscriptionStatus,
)
from app.models.user import (
    PasswordReset,
    PasswordUpdate,
    RefreshTokenRequest,
    SuperAdminCreate,
    TokenResponse as UserTokenResponse,
    UserBase,
    UserCreate,
    UserInvite,
    UserListResponse,
    UserQueryParams,
    UserResponse,
    UserRole,
    UserRoleUpdate,
    UserSignIn,
    UserSignUp,
    UserStatus,
    UserStatusUpdate,
    UserUpdate,
    UserWithOrganization,
)

__all__ = [
    # Meeting models
    "ChatMessageInput",
    "MeetingBase",
    "MeetingCreate",
    "MeetingChatMessageResponse",
    "MeetingListResponse",
    "MeetingQueryParams",
    "MeetingResponse",
    "MeetingStatus",
    "MeetingType",
    "MeetingUpdate",
    "ParticipantInput",
    "ParticipantResponse",
    "ParticipantRole",
    "ParticipantStatus",
    "ParticipantStatusUpdate",
    "LiveKitTokenResponse",
    # Message models
    "ConversationListResponse",
    "ConversationResponse",
    "MessageBase",
    "MessageCreate",
    "MessageReactionCreate",
    "MessageReactionResponse",
    "MessageResponse",
    "MessageUpdate",
    "PinMessageRequest",
    # Organization models
    "ApproveOrgAdminRequest",
    "OrganizationBase",
    "OrganizationCreate",
    "OrganizationListResponse",
    "OrganizationQueryParams",
    "OrganizationResponse",
    "OrganizationSetup",
    "OrganizationSetupResponse",
    "OrganizationSubscriptionUpdate",
    "OrganizationUpdate",
    "OrganizationWithStats",
    "OrgAdminSignup",
    "OrgAdminSignupResponse",
    "SubscriptionPlan",
    "SubscriptionStatus",
    # User models
    "PasswordReset",
    "PasswordUpdate",
    "RefreshTokenRequest",
    "SuperAdminCreate",
    "UserTokenResponse",
    "UserBase",
    "UserCreate",
    "UserInvite",
    "UserListResponse",
    "UserQueryParams",
    "UserResponse",
    "UserRole",
    "UserRoleUpdate",
    "UserSignIn",
    "UserSignUp",
    "UserStatus",
    "UserStatusUpdate",
    "UserUpdate",
    "UserWithOrganization",
]

